apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-pusher
  namespace: cours-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-pusher
  template:
    metadata:
      labels:
        app: post-pusher
    spec:
      containers:
        - name: post-pusher
          image: ghcr.io/akrouthassen/post-pusher:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /service-account.json
            - name: KAFKA_HOST
              value: "kafka-broker-service.cours-kubernetes:9092"
            - name: PUSH_INTERVAL_SECONDS
              value: "10"
          command: ["python", "main.py", "--multiple"]
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: gcp-sa
              mountPath: /service-account.json
              subPath: service-account.json
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-service-account