
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
  namespace: cours-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
        - name: post-api
          image: 2024_kubernetes_post_api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATASET_ID
              valueFrom:
                configMapKeyRef:
                  name: posts-config
                  key: DATASET_ID
            - name: TABLE_ID
              valueFrom:
                configMapKeyRef:
                  name: posts-config
                  key: TABLE_ID
          volumeMounts:
            - name: gcp-sa
              mountPath: /app/service-account.json
              subPath: service-account.json
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: post-api
  namespace: cours-kubernetes
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      
