apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-consumer
  namespace: cours-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-consumer
  template:
    metadata:
      labels:
        app: post-consumer
    spec:
      containers:
      - name: post-consumer
        image: ghcr.io/akrouthassen/post-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: KAFKA_HOST

          - name: DATASET_ID
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: DATASET_ID

          - name: TABLE_ID
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: TABLE_ID

          - name: GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: GROUP_ID

          - name: TOPIC
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: TOPIC

          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/service-account.json"

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: gcp-sa
          mountPath: /service-account.json
          subPath: service-account.json

      volumes:
      - name: gcp-sa
        secret:
          secretName: gcp-service-account