apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-consumer
  namespace: cours-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-consumer
  template:
    metadata:
      labels:
        app: post-consumer
    spec:
      containers:
        - name: post-consumer
          image: 2024_kubernetes_post_consumer
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_HOST
              value: "kafka-broker-service:9092" # Nom du service Kafka 
            - name: DATASET_ID
              value: "data_devops"
            - name: TABLE_ID
              value: "posts"
          volumeMounts:
            - name: gcp-sa
              mountPath: /app/service-account.json
              subPath: service-account.json
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-service-account